### Prepocesser will read from PricingModelConfiguration.yaml file ####

# paths
DATASET_FOLDER : "DataSets"
filename : "Housing_Data.csv"
#path_to_dataset : "path_to_my_dataset"
target_name : "SalePrice"
output_scaler_path : 'path_to_store_scaler'
output_model_path : 'path_to_store_model'
#====== END =======
## preproc
#var1_mean_val : 1
#var2_mean_val : 2
#
#var4_cap_value : 1000
#var5_cap_value : 5000
#
#var8_frequent_labels : ['frequent1', 'frequent2', 'frequent3']
#
## features
#features : ['var1', 'var2', 'var3', 'var4', 'etc']